[package]
name = "ypir_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "ypir_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.0", features = ["extension-module"] }

ypir = { path = ".." }
